name: Docker Images

on:
  push:
    branches:
      - '**'
    tags:
      - "v*"
    paths:
      - .github/workflows/docker.yml
      - "Dockerfile"

jobs:
  docker:
    strategy:
      matrix:
        runs-on: ["ubuntu-latest", "docker-arm"]
    runs-on: ${{ matrix.runs-on }}
    steps:

    - name: Login to Docker
      uses: docker/login-action@v2
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login To GitHub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: cyb3rjak3/workerd,ghcr.io/cyb3r-jak3/workerd
        tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
        labels: |
          org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/docker-udpt.git
          org.label-schema.schema-version=1.0.0-rc1
          maintainer=Cyb3r Jak3 git@cyberjake.xyz
          org.opencontainers.image.vendor=cyb3rjak3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Checkout
      uses: actions/checkout@v3

    - name: select platform
      env:
        RUNS_ON: ${{ matrix.runs-on }}
      run: |
        if [ $RUNS_ON = "docker-arm" ]; then
            echo "PLATFORM=linux/arm64" >> $GITHUB_ENV
        else
            echo "PLATFORM=linux/amd64" >> $GITHUB_ENV
        fi

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/cyb3r-jak3/workerd-cache
        cache-to: type=registry,mode=max,ref=ghcr.io/cyb3r-jak3/workerd-cache
        platforms: ${{ env.PLATFORM }}